dj_onlineshop/order/urls.py
from django.contrib import admin
from django.urls import path
from order import views

app_name = 'cart'

urlpatterns = [

    path('add-to-cart/', views.AddProductCart.as_view(), name='add-to-cart'),
    path('', views.CartDetail.as_view(), name='cart-detail'),
    path('recalculate-cart/', views.EditCart.as_view(), name='recalculate-cart'),
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('order/', views.OrderListInProfile.as_view(), name='order-list'),
    path('order/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('order-update/<int:pk>/', views.StatusOrderUpdate.as_view(), name='order-update'),


]

dj_onlineshop/profiles/urls.py
from django.contrib import admin
from django.urls import path
from profiles import views

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('user/<int:pk>/', views.ProfileDetail.as_view(), name='profile'),
    path('edit/<int:pk>/', views.ProfileUpdate.as_view(), name='edit_profile'),
    path('logout/', views.Logout_view.as_view(), name='logout'),
]

dj_onlineshop/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from references import views
from product.views import FilterAuthor

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('', include('product.urls')),
    path('', include('profiles.urls')),
    path('cart/', include('order.urls', namespace='cart')),
    path('authors/', views.AuthorList.as_view(), name='authors-list'),
    path('authors/filter/', FilterAuthor.as_view(), name='author-filter'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author-detail'),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name='author-delete'),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author-create/', views.AuthorCreate.as_view(), name='author-create'),
    path('genres/', views.GenreList.as_view(), name='genres-list'),
    path('genre/<int:pk>/', views.GenreDetail.as_view(), name='genre-detail'),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name='genre-delete'),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name='genre-update'),
    path('genre-create/', views.GenreCreate.as_view(), name='genre-create'),

    
]

dj_onlineshop/profiles/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    username = models.OneToOneField(
        User,
        on_delete=models.PROTECT,
        verbose_name="Имя пользователя", 
        max_length=30,
        primary_key=True)
    first_name = models.CharField(
        verbose_name="Фамилия",
        max_length=30,
        null=True, 
        blank=True)
    last_name = models.CharField(
        verbose_name="Имя",
        max_length=30,
        null=True, 
        blank=True)    
    email = models.EmailField(
        max_length=100, 
        help_text='Enter a valid email addres')      
    group_user = models.ForeignKey(
        Group,
        on_delete=models.PROTECT,
        null=True,
        blank=True)    
    country = models.CharField(
        verbose_name="Страна",
        max_length=30,
        null=True, 
        blank=True)
    city = models.CharField(
        verbose_name="Город",
        max_length=40,
        null=True, 
        blank=True)
    zip_code = models.PositiveSmallIntegerField(
        verbose_name="Индекс",
        null=True, 
        blank=True)
    address_first = models.CharField(
        verbose_name="Адрес1",
        max_length=100,
        null=True, 
        blank=True)
    address_second = models.CharField(
        verbose_name="Адрес2",
        max_length=100,
        null=True, 
        blank=True)
    info = models.TextField(
        verbose_name="Дополнительная информация",
        max_length=1000,
        null=True,
        blank=True)              

    def get_absolute_url(self):
        return reverse("user", kwargs={"pk": self.username.pk})
    

    def __str__(self):
        return f'{self.username}'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профиля'    

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(username=instance)

@receiver
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

dj_onlineshop/profiles/forms.py
from django import forms
from django.db.models import fields
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from profiles.models import Profile

class SingUpForm(UserCreationForm):
    password1 = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
        )
    password2 = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'})
        )
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            user.groups.add(Group.objects.get(name='Customers'))
        return user

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'            
        ]

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1'
        ]

class ProfileUpdate(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'username',
            'first_name',
            'last_name',
            'email', 
            'country', 
            'city', 
            'zip_code', 
            'address_first', 
            'address_second', 
            'info',
            ]                       

dj_onlineshop/profiles/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from profiles import models, forms
from order.models import Order
from proj import settings
# Create your views here.


class SignUpView(CreateView):
    model = models.User
    form_class = forms.SingUpForm
    success_url = reverse_lazy('home')
    template_name = 'register.html'

class Login(LoginView):
    model = models.User
    form_class = forms.LoginForm
    success_url = reverse_lazy('home')
    template_name = 'login.html'

class Logout_view(LogoutView):
    redirect_field_name = settings.LOGOUT_REDIRECT_URL

class ProfileDetail(LoginRequiredMixin, DetailView):
    template_name = 'profiles/account_detail.html'
    queryset = models.Profile.objects.all()
    
class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = models.Profile
    template_name = 'profiles/account_update.html'
    success_url = reverse_lazy('home')
    form_class = forms.ProfileUpdate

dj_onlineshop/templates/profiles/account_detail.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<div class="container emp-profile">
    <div class="row">
        <div class="col-md-12">
            <div class="profile-head">
                        <h1>
                            Профиль {{ object.username }}
                        </h1>
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="{% url 'profile' user.pk %}" role="tab" aria-controls="home" aria-selected="true">Инфо</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="{% url 'cart:order-list' %}" role="tab" aria-controls="profile" aria-selected="false">Заказы</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="tab-content profile-tab" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Группа пользователей</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.group_user }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Никнейм</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.username }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Имя</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.first_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Фамилия</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.last_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Электронная почта</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.email }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Страна</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.country }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Город</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.city }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Индекс</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.zip_code }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Адрес</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.address_first }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Доп. Адрес</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.address_second }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Дополнительная информация</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.info }}</p>
                        </div>
                    </div>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{% url "logout" %}"><button type="button" class="btn btn-primary">Выйти из аккаунта</button></a>
                        <a href="{% url "edit_profile" profile.pk %}"><button type="button" class="btn btn-primary">Редактировать Профиль</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>              
</div>

{% endblock main %}

dj_onlineshop/templates/profiles/account_detail_order.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<div class="container emp-profile">
    <div class="row">
        <div class="col-md-12">
            <div class="profile-head">
                        <h1>
                            Заказы
                        </h1>
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link" id="home-tab" data-toggle="tab" href="{% url 'profile' user.pk %}" role="tab" aria-controls="home" aria-selected="true">Инфо</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" id="profile-tab" data-toggle="tab" href="{% url 'cart:order-list' %}" role="tab" aria-controls="profile" aria-selected="false">Заказы</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
 <div class="row">
        <div class="col-md-12">
            <div class="tab-content profile-tab" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="row">Номер заказа</th>
                    <th scope="row">Адрес</th>
                    <th scope="row">Сумма</th>
                    <th scope="row">Дата заказа</th>
                    <th scope="row">Статус заказа</th>
                    <th scope="row">Действия с заказом</th>
                </tr>
                </thead>
                {% for order in category %}
                <tr>
                    <th scope="row">{{ order.pk }}</th>
                    <td>{{ order.address }}</a></td>
                    <td>{{ order.total_sum_order }}</td>
                    <td>{{ order.created }}</td>
                    <td>{{ order.actions }}</td>
                    <td><a href="{% url 'cart:order-update' order.pk %}" class="btn btn-outline-secondary">Изменить статус</a></td>
                </tr>
                {% endfor %}
        </table>
                        
                </div>
            </div>
        </div>
    </div>              
</div>
 

{% endblock main %}

dj_onlineshop/templates/profiles/account_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
    <h1>Редактирование профиля</h1>
    <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
      {{ form|crispy }}<br>
       <button type="submit" class="btn btn-block">Edit</button>
    </form>
{% endblock main %}

dj_onlineshop/templates/profiles/order_detail.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
    <h1>Book name {{ object.cart }}</h1>
    {{ object.username }} <br>
    {{ object.customer_name }} <br>
    {{ object.address }} <br>
    {{ object.phone_number }} <br>
    {{ object.total_sum_order }} <br>
    {{ object.actions }} <br>
    {{ object.created }} <br>
    {{ object.updated }} <br>  
{% endblock main %}

dj_onlineshop/templates/profiles/order_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
    <h1>Изменение статуса заказа</h1>
    <form action="" method="post"> {% csrf_token %}
      {{ form|crispy }}<br>
        <button type="submit" class="btn btn-block">Изменить</button>
    </form>
{% endblock main %}