dj_onlineshop/order/urls.py
from django.contrib import admin
from django.urls import path
from order import views

app_name = 'cart'

urlpatterns = [

    path('add-to-cart/', views.AddProductCart.as_view(), name='add-to-cart'),
    path('', views.CartDetail.as_view(), name='cart-detail'),
    path('recalculate-cart/', views.EditCart.as_view(), name='recalculate-cart'),
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('order/', views.OrderListInProfile.as_view(), name='order-list'),
    path('order/<int:pk>/', views.OrderDetail.as_view(), name='order-detail'),
    path('order-update/<int:pk>/', views.StatusOrderUpdate.as_view(), name='order-update'),


]

dj_onlineshop/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from references import views
from product.views import FilterAuthor

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('', include('product.urls')),
    path('', include('profiles.urls')),
    path('cart/', include('order.urls', namespace='cart')),
    path('authors/', views.AuthorList.as_view(), name='authors-list'),
    path('authors/filter/', FilterAuthor.as_view(), name='author-filter'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author-detail'),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name='author-delete'),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author-create/', views.AuthorCreate.as_view(), name='author-create'),
    path('genres/', views.GenreList.as_view(), name='genres-list'),
    path('genre/<int:pk>/', views.GenreDetail.as_view(), name='genre-detail'),
    path('genre-delete/<int:pk>/', views.GenreDelete.as_view(), name='genre-delete'),
    path('genre-update/<int:pk>/', views.GenreUpdate.as_view(), name='genre-update'),
    path('genre-create/', views.GenreCreate.as_view(), name='genre-create'),

    
]

dj_onlineshop/templates/account_detail.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<div class="container emp-profile">
    <div class="row">
        <div class="col-md-6">
            <div class="profile-head">
                        <h1>
                            Профиль {{ object.username }}
                        </h1>
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Инфо</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Заказы</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="tab-content profile-tab" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row">
                        <div class="col-md-6">
                            <label>Группа пользователей</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.group_user }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Никнейм</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.username }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Имя</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.first_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Фамилия</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.last_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Электронная почта</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.email }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Страна</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.country }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Город</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.city }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Индекс</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.zip_code }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Адрес</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.address_first }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Доп. Адрес</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.address_second }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Дополнительная информация</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{ object.info }}</p>
                        </div>
                    </div>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{% url "logout" %}"><button type="button" class="btn btn-primary">Выйти из аккаунта</button></a>
                        <a href="{% url "edit_profile" profile.pk %}"><button type="button" class="btn btn-primary">Редактировать Профиль</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>              
</div>

{% endblock main %}

dj_onlineshop/templates/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<h1>Корзина</h1>

<div class="container">
    <br>
    <h1>Добавить товар {{ object.product }}</h1>
        <form action="" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-success'>Добавить</button>
        </form>
    </div>
    

{% endblock main %}
     
    

dj_onlineshop/templates/add_cart.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<h1>Корзина</h1>
<form action="{% url 'cart:recalculate-cart' %}" method="GET">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Товар</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
                <th scope="col">Сумма</th>
            </tr>    
        </thead>
        {% for product_item in object.products_item.all %}
            <tr>
                <td>{{ product_item.product.name_book }}</td>
                <td>{{ product_item.product.price }}</td>
                <td><input type="number" name="product_item_{{ product_item.pk }}" min='0' value="{{ product_item.quantity }}"></td>
                <td>{{ product_item.total_price }}</td>
            </tr>    
    {% endfor %}
            <tr>
                <td colspan="3">Итоговая сумма</td>
                <td colspan="3">{{ object.total_sum }}</td>
            </tr>
    </table>
    <button type="submit" name="btn" class="btn btn-success" value="recalculate">Обновить корзину</button>
    <button type="submit" name="btn" class="btn btn-danger" value="checkout">Оформить заказ</button>
</form>
{% endblock main %}
     
    

dj_onlineshop/templates/base.html
{% load static %}
{% load profile_tools %}

<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   
</head>
<body>
<div class="container">
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BOOK-Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/books">Каталог книг</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/authors">Авторы</a>
          </li>
          {% if request.user|has_group:"Managers" %}
          <li class="nav-item">
            <a class="nav-link" href="/genres">Жанры</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' user.pk %}">Профиль</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/register">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Войти в профиль</a>
          </li>
          {% endif %}
          
          </ul>
        
          </div>   
       </div> 
       <div class="float-right">
            <a href="{% url "cart:cart-detail" %}">
               <button type="button" class="btn btn-outline-dark navbar-btn">Корзина</button>
            </a>
          </div>  
  </nav>
     
    
         {% block main %}
         
         {% endblock main %}
    
</div>    
</body>
</html>

dj_onlineshop/templates/cart.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<h1>Корзина</h1>

<form action="{% url 'cart:recalculate-cart' %}" method="GET">
<button type="submit" name="btn" class="btn btn-success btn btn-block" role="button" value="recalculate">Обновить корзину</button>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Товар</th>
                <th scope="col"></th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
                <th scope="col">Сумма</th>
            </tr>    
        </thead>
        {% for product_item in object.products_item.all %}
            <tr>
                <td><img class="img-fluid img-thumbnail" width="150" src="{{ product_item.product.photo.url }}" alt="Card image cap"></td>
                <td>{{ product_item.product.name_book }}</td>
                <td>{{ product_item.product.price }}</td>
                <td><input type="number" name="product_item_{{ product_item.pk }}" min='0' value="{{ product_item.quantity }}"></td>
                <td>{{ product_item.total_price }}</td>
            </tr>    
    {% endfor %}
            <tr>
                <td colspan="4">Итоговая сумма</td>
                <td colspan="4">{{ object.total_sum }}</td>
            </tr>
    </table>
    

</form>
    <a href="{% url 'cart:checkout' %}"><button type="submit" name="btn" class="btn btn-info btn btn-block" role="button" value="">Оформить заказ</button></a>

{% endblock main %}
     
    

dj_onlineshop/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}

{% block main %}
<h1>Корзина</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Товар</th>
                <th scope="col"></th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
                <th scope="col">Сумма</th>
            </tr>    
        </thead>
        {% for order_item in object.products_item.all %}
            <tr>
                <td><img class="img-fluid img-thumbnail" width="150" src="{{ order_item.product.photo.url }}" alt="Card image cap"></td>
                <td>{{ order_item.product.name_book }}</td>
                <td>{{ order_item.product.price }}</td>
                <td><input type="number" name="order_item_{{ order_item.pk }}" min='0' value="{{ order_item.quantity }}"></td>
                <td>{{ order_item.total_price }}</td>
            </tr>    
    {% endfor %}
            <tr>
                <td colspan="4">Итоговая сумма</td>
                <td colspan="4">{{ object.cart.total_sum }}</td>
            </tr>
    </table>
    <form action='' method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-success'>Оформить</button>
        </form>

{% endblock main %}
     
    

dj_onlineshop/templates/home.html
{% extends 'base.html' %}

{% block title %} 
{{ page_title }} 
{% endblock title %}


{% block main %}



<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
        <ul class="list-group">
        <li class="list-group-item active" aria-current="true"><h5 class="display-5">Жанры</h5></li>
        {% for genre in category %}
        <li class="list-group-item"><a href="{% url 'product_filter' %}?genre={{ genre.pk }}">{{ genre.name_genre }}</a></li>
        {% endfor %}
        
      </ul>
  </div>

    <div class="col-sm-6">
      <li class="list-group-item active" aria-current="true"><h5 class="display-5">Новинки</h5></li>
        {% for product in last_product %}
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img class="card-img-top" height="250" src="{{ product.photo.url }}" alt="Card image cap">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><a href="{% url 'book-detail' product.pk %}">{{ product.name_book }}</a></h5>
                <p class="card-text">{{ product.price }}</p>
                <p class="card-text"><small class="text-muted">{{ product.availability }}</small></p>
               <a href="{% url 'cart:add-to-cart' %}?product={{ product.pk }}" class="btn btn-primary">Добавить в корзину</a>
               
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
</div>
{% endblock main %}
     
    

dj_onlineshop/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}


{% block main %}
<h1>Login</h1>
    <form action="" method="post"> {% csrf_token %}
      {{ form|crispy }}<br>
        <button type="submit" class="btn btn-block">Login</button>
    </form>
{% endblock main %}
     
    

dj_onlineshop/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} 
{{ page_title }} 
{% endblock title %}


{% block main %}
<h1>Sing Up</h1>
    <form action="" method="post"> {% csrf_token %}
      {{ form|crispy }}<br>
        <button type="submit" class="btn btn-block">Register</button>
    </form>
{% endblock main %}
     
    

dj_onlineshop/templates/search.html
{% extends 'base.html' %}

{% block title %} 
Поиск
{% endblock title %}

{% block main %}

{% endblock main %}
     
    